environment_variables:
  - name: NEW_RELIC_APP_NAME
    value: http-backend-prod

  - name: NEW_RELIC_LICENSE_KEY
    value: 10db9c32c467cfb33c97769ce49308ebFFFFNRAL

  - name: NEW_RELIC_ENABLED
    value: false

  - name: SPRING_PROFILES_ACTIVE
    value: prod