environment_variables:
  - name: NEW_RELIC_APP_NAME
    value: http-backend-prod

  - name: NEW_RELIC_LICENSE_KEY
    value: 3c396a9096bfdfa9cf80b8f5527fe2ba1b64NRAL

  - name: NEW_RELIC_ENABLED
    value: false

  - name: SPRING_PROFILES_ACTIVE
    value: prod